#!/bin/bash
export HOME=/root
if [ ! -d /var/www ]; then
  mkdir -p /var/www
fi
cd /var/www/

while [ -f /var/run/update-repo.lock ]; do
  sleep 1
done

touch /var/run/update-repo.lock

function finish {
  rm /var/run/update-repo.lock
  exit 1
}

apt-ftparchive packages . > Packages || finish
gzip -c Packages > Packages.gz || finish
apt-ftparchive release . > Release || finish
gpg --batch --yes --passphrase-file /root/.gnupg/passphrase_apt --digest-algo SHA512 --clearsign -o InRelease Release || finish
gpg --batch --yes --passphrase-file /root/.gnupg/passphrase_apt --digest-algo SHA512 -abs -o Release.gpg Release || finish
chown -fR www-data:www-data /var/www/ || finish
rm /var/run/update-repo.lock

